// <auto-generated />
namespace Navigator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SingularTableName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SingularTableName));
        
        string IMigrationMetadata.Id
        {
            get { return "202004091602552_SingularTableName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
